# Generated by Django 3.2.3 on 2021-06-10 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('seats', models.PositiveIntegerField(default=1, null=True)),
                ('board', models.BooleanField(default=False)),
                ('projector', models.BooleanField(default=False)),
                ('description', models.TextField(default='Нет описания')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('title', models.CharField(default='(Без названия)', max_length=140)),
                ('manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_manager', to=settings.AUTH_USER_MODEL)),
                ('organizator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_organizator', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_role', to='new_site.room')),
            ],
        ),
    ]
