# Generated by Django 3.2.3 on 2021-06-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_role', to='new_site.room'),
        ),
    ]
