# Generated by Django 3.2.3 on 2021-06-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coworker',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_C', to='new_site.user', unique=True),
        ),
        migrations.AlterField(
            model_name='coworker',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_C', to='new_site.role', unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_desk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_proj',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Organizator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_organizator', to='new_site.coworker'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_manager', to='new_site.coworker'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_role', to='new_site.room'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
