# Generated by Django 3.2.3 on 2021-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_site', '0002_auto_20210602_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
