# Generated by Django 3.2.3 on 2021-06-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_site', '0002_auto_20210601_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='somebody', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='somebody', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_C', to='new_site.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default='Coworker', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Organizator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_organizator', to='new_site.user'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_manager', to='new_site.user'),
        ),
        migrations.DeleteModel(
            name='Coworker',
        ),
    ]
