# Generated by Django 3.2.3 on 2021-06-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_site', '0002_alter_schedule_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
