# Generated by Django 3.2.3 on 2021-06-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_site', '0004_auto_20210603_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(default='(Без названия)', max_length=140),
        ),
    ]
