# Generated by Django 3.2.3 on 2021-06-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_site', '0005_schedule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='seats',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
